return {
    cmd = { 'emmet-language-server', '--stdio' },
    filetypes = {
        'astro',
        'css',
        'eruby',
        'htmldjango',
        'html',
        'htmlangular',
        'javascriptreact',
        'less',
        'pug',
        'sass',
        'scss',
        'svelte',
        'templ',
        'typescriptreact',
        'vue',
    },
    root_markers = { '.git' },
}
